hector_mapping:
  map_frame: map
  base_frame: base_link
  odom_frame: odom
  
  pub_map_odom_transform: true
  pub_map_scanmatch_transform: true
  
  map_resolution: 0.100
  map_size: 2048
  map_multi_res_levels: 3
  map_update_angle_thresh: 0.06
  
  scan_topic: /scan
  
rtabmap:
    rtabmap:
        frame_id: base_link
        map_frame_id: map
        odom_frame_id: odom
      
        subscribe_depth: false
        subscribe_rgb: false
        subscribe_rgbd: true
        subscribe_scan: true
      
        publish_tf: false
      
        Reg/Strategy: 2
        Reg/Force3DoF: true
        RGBD/ProximityBySpace: false
      
        RGBD/ProximityPathMaxNeighbors: 10
        Grid/Scan2dUnknownSpaceFilled: true
      
        Grid/FromDepth: true
        Grid/MaxGroundHeight: 0.2
        Grid/MaxObstacleHeight: 2.0
        Grid/NormalsSegmentation: false
