hector_mapping:
  map_frame: map
  base_frame: base_link
  odom_frame: odom
  
  pub_map_odom_transform: false
  pub_map_scanmatch_transform: true
  pub_odometry: true
  
  map_resolution: 0.050
  map_size: 2048
  map_multi_res_levels: 2
  map_update_angle_thresh: 0.06
  
  scan_topic: /scan

icp_odometry:
  frame_id: base_link
  odom_frame_id: odom
  publish_tf: true
  
  Icp/PointToPlane: false
  Icp/VoxelSize: 0.05
  Icp/Epsilon: 0.001
  Icp/PointToPlaneK: 5
  Icp/PointToPlaneRadius: 0.3
  Icp/MaxCorrespondenceDistance: 0.1
  Icp/PM: true
  Icp/PMOutlierRatio: 0.95
  Odom/Strategy: 0
  Odom/GuessMotion: true
  Odom/ResetCountdown: 0
  Odom/ScanKeyFrameThr: 0.9
  
rtabmap:
    rtabmap:
      frame_id: base_link
      map_frame_id: map
      odom_frame_id: odom
      
      subscribe_depth: false
      subscribe_rgb: false
      subscribe_rgbd: true
      subscribe_scan: true
      
      publish_tf: false
      
      Reg/Strategy: 2
      Reg/Force3DoF: true
      RGBD/ProximityBySpace: false
      
      RGBD/ProximityPathMaxNeighbors: 10
      Grid/Scan2dUnknownSpaceFilled: true
      
      Grid/FromDepth: false
