hector_mapping:
#  map_frame: hector_map
  map_frame: map
  base_frame: base_link
  odom_frame: odom
  
  pub_map_odom_transform: false
  pub_map_scanmatch_transform: true
  pub_odometry: true
  
  map_resolution: 0.050
  map_size: 2048
  map_multi_res_levels: 2
  map_update_angle_thresh: 0.06
  
  scan_topic: /hokuyo_laser/laser_scan

rtabmap:
    rtabmap:
      frame_id: base_link

      subscribe_depth: false
      subscribe_rgb: false
      subscribe_rgbd: true
      subscribe_scan: true
      
      Reg/Strategy: 2
      Reg/Force3DoF: true
      RGBD/ProximityBySpace: false
      RGBD/ProximityPathMaxNeighbors: 10
      
      Grid/FromDepth: true
      
      odom_frame_id: odom
      odom_tf_linear_variance: 0.0005
      odom_tf_angular_variance: 0.0005
      

points_xyzrgb:
  voxel_size: 0.01

