drivetrain:
    frc_joint_state_controller:
        # The joint state controller handles publishing transforms for any moving joints
        type: "joint_state_controller/JointStateController"
        publish_rate: 50

    fl_pivot_controller:
        type: position_controllers/JointPositionController
        joint: base_link_to_fl_swerve_pivot
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

    fl_drive_controller:
        type: velocity_controllers/JointVelocityController
        joint: fl_swerve_pivot_to_fl_swerve_wheel
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

    fr_pivot_controller:
        type: position_controllers/JointPositionController
        joint: base_link_to_fr_swerve_pivot
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

    fr_drive_controller:
        type: velocity_controllers/JointVelocityController
        joint: fr_swerve_pivot_to_fr_swerve_wheel
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

    rl_pivot_controller:
        type: position_controllers/JointPositionController
        joint: base_link_to_rl_swerve_pivot
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

    rl_drive_controller:
        type: velocity_controllers/JointVelocityController
        joint: rl_swerve_pivot_to_rl_swerve_wheel
        publish_rate: 50e_wheel
        pid: { p: 1.0, i: 0.0, d: 0.0 }

    rr_pivot_controller:
        type: position_controllers/JointPositionController
        joint: base_link_to_rr_swerve_pivot
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

    rr_drive_controller:
        type: velocity_controllers/JointVelocityController
        joint: rr_swerve_pivot_to_rr_swerve_wheel
        pid: { p: 1.0, i: 0.0, d: 0.0 }
        publish_rate: 50

/gazebo_ros_control/pid_gains:
        base_link_to_fl_swerve_pivot: {p: 25.0, i: 0.1, d: 0.0}
        fl_swerve_pivot_to_fl_swerve_wheel: {p: 10.0, i: 0.01, d: 0.0}
        base_link_to_fr_swerve_pivot: {p: 25.0, i: 0.1, d: 0.0}
        fr_swerve_pivot_to_fr_swerve_wheel: {p: 10.0, i: 0.01, d: 0.0}
        base_link_to_rl_swerve_pivot: {p: 25.0, i: 0.1, d: 0.0}
        rl_swerve_pivot_to_rl_swerve_wheel: {p: 10.0, i: 0.01, d: 0.0}
        base_link_to_rr_swerve_pivot: {p: 25.0, i: 0.1, d: 0.0}
        rr_swerve_pivot_to_rr_swerve_wheel: {p: 10.0, i: 0.01, d: 0.0}
        
        
        
