<?xml version="1.0"?>
<root xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find frc_robot)/urdf/inertia.urdf.xacro" />
    
    <xacro:macro name="elevator_attachment" params="name parent ax ay az rr rp ry">
      
    <!--                          Elevator                           -->
      
      <xacro:property name="elevator_length" value="0.0762" />
      <xacro:property name="elevator_width" value="0.508" />
      <xacro:property name="elevator_height" value="0.9144" />
      <xacro:property name="elevator_mass" value="1" />
      
      <link name="elevator">
        <visual>
          <geometry>
            <box size="${elevator_length} ${elevator_width} ${elevator_height}"/>
          </geometry>
          <origin xyz="0 0 ${elevator_height/2}"/>
          <material name="blue"/>
        </visual>
        <collision>
          <geometry>
            <box size="${elevator_length} ${elevator_width} ${elevator_height}"/>
          </geometry>
          <origin xyz="0 0 ${elevator_height/2}"/>
        </collision>
        <inertial>
          <mass value="1.0"/>
          <xacro:box_inertia
          m="${elevator_mass}"
          x="${elevator_length}"
          y="${elevator_width}"
          z="${elevator_height}" />
          <origin xyz="0 0 ${elevator_height/2}"/>
        </inertial>
      </link>
      <joint name="${parent}_to_elevator" type="fixed">
        <parent link="${parent}"/>
        <child link="elevator"/>
        <origin rpy="${rr} ${rp} ${ry}" xyz="${ax} ${ay} ${az}"/>
      </joint>
      



    <!--                          Elevator Carriage                           -->
      
      <xacro:property name="elevator_carriage_length" value="0.1524" />
      <xacro:property name="elevator_carriage_width" value="0.4064" />
      <xacro:property name="elevator_carriage_height" value="0.1524" />
      <xacro:property name="elevator_carriage_mass" value="1" />
      
      <link name="elevator_carriage">
        <visual>
          <geometry>
            <box size=
            "${elevator_carriage_length}
            ${elevator_carriage_width}
            ${elevator_carriage_height}"/>
          </geometry>
          <origin xyz="${elevator_carriage_length/2} 0 ${elevator_carriage_height/2}"/>
          <material name="blue"/>
        </visual>
        <collision>
          <geometry>
            <box size=
            "${elevator_carriage_length}
            ${elevator_carriage_width}
            ${elevator_carriage_height}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${elevator_carriage_mass}"/>
          <xacro:box_inertia
          m="${elevator_carriage_mass}"
          x="${elevator_carriage_length}"
          y="${elevator_carriage_width}"
          z="${elevator_carriage_height}" />
          <origin xyz="${elevator_carriage_length/2} 0 ${elevator_carriage_height/2}"/>
        </inertial>
      </link>
      <joint name="elevator_to_elevator_carriage" type="prismatic">
        <parent link="elevator"/>
        <child link="elevator_carriage"/>
        <limit effort="1000.0" lower="0" upper="1.8288" velocity="0.5"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>
      

    <!--                          Intake Arm                           -->
      
      <xacro:property name="intake_arm_length" value="0.3048" />
      <xacro:property name="intake_arm_width" value="0.3556" />
      <xacro:property name="intake_arm_height" value="0.0762" />
      <xacro:property name="intake_arm_mass" value="1" />
      
      <link name="intake_arm">
        <visual>
          <geometry>
            <box size=
            "${intake_arm_length}
            ${intake_arm_width}
            ${intake_arm_height}"/>
          </geometry>
          <origin xyz="0.1524 0 0"/>
          <material name="blue"/>
        </visual>
        <collision>
          <geometry>
            <box size=
            "${intake_arm_length}
            ${intake_arm_width}
            ${intake_arm_height}"/>
          </geometry>
          <origin xyz="${intake_arm_length/2} 0 0"/>
        </collision>
        <inertial>
          <mass value="${intake_arm_mass}"/>
          <xacro:box_inertia
          m="${intake_arm_mass}"
          x="${intake_arm_length}"
          y="${intake_arm_width}"
          z="${intake_arm_height}" />
          <origin xyz="${intake_arm_length/2} 0 0"/>
        </inertial>
      </link>
      <joint name="elevator_carraige_to_intake_arm" type="revolute">
        <axis xyz="0 1 0"/>
        <parent link="elevator_carriage"/>
        <child link="intake_arm"/>
        <limit effort="1000.0" lower="-1.57079632679" upper="0" velocity="0.5"/>
        <origin rpy="0 0 0" xyz="0.127 0 0.127"/>
      </joint>
      



    <!--                          Intake                           -->
      
      <xacro:property name="intake_length" value="0.2286" />
      <xacro:property name="intake_width" value="0.4064" />
      <xacro:property name="intake_height" value="0.2286" />
      <xacro:property name="intake_mass" value="1" />
      
      <link name="intake">
        <visual>
          <geometry>
            <box size=
            "${intake_length}
            ${intake_width}
            ${intake_height}"/>
          </geometry>
          <origin xyz="${intake_length/2} 0 -${intake_length/2-0.0381}"/>
          <material name="blue"/>
        </visual>
        <collision>
          <geometry>
            <box size=
            "${intake_length}
            ${intake_width}
            ${intake_height}"/>
          </geometry>
          <origin xyz="${intake_length/2} 0 -${intake_length/2-0.0381}"/>
        </collision>
        <inertial>
          <mass value="${intake_mass}"/>
          <xacro:box_inertia
          m="${intake_mass}"
          x="${intake_length}"
          y="${intake_width}"
          z="${intake_height}" />
          <origin xyz="${intake_length/2} 0 -${intake_length/2-0.0381}"/>
        </inertial>
      </link>
      <joint name="intake_arm_to_intake" type="fixed">
        <parent link="intake_arm"/>
        <child link="intake"/>
        <origin rpy="0 0 0" xyz="0.3048 0 0"/>
      </joint>


    <!--                          Motion Controllers                           -->
      
      <transmission name="elevator_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="$elevator_motor">
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="elevator_to_elevator_carriage">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      </transmission>
      
      
      
      <transmission name="wrist_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="$wrist_motor">
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="elevator_carraige_to_intake_arm">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      </transmission>
  </xacro:macro>
</root>
