drive_controller:
    fl_drive_conversion_param: 15.0
    fr_drive_conversion_param: 15.0
    rl_drive_conversion_param: 15.0
    rr_drive_conversion_param: 15.0
    
    cmd_vel_param: /drive_controller/cmd_vel
    
    fl_pivot_command_param: /fl_pivot_controller/command
    fl_drive_command_param: /fl_drive_controller/command
    fr_pivot_command_param: /fr_pivot_controller/command
    fr_drive_command_param: /fr_drive_controller/command
    rl_pivot_command_param: /rl_pivot_controller/command
    rl_drive_command_param: /rl_drive_controller/command
    rr_pivot_command_param: /rr_pivot_controller/command
    rr_drive_command_param: /rr_drive_controller/command
    
    imu_topic: /imu
