hector_mapping:
  map_frame: map
  base_frame: base_link
  odom_frame: odom
  
  pub_map_odom_transform: true
  pub_map_scanmatch_transform: false
  
  map_resolution: 0.100
  map_size: 2048
  map_multi_res_levels: 3
  map_update_angle_thresh: 0.06
  
  scan_topic: /scan

icp_odometry:
    frame_id: base_link
    publish_tf: true
    Icp/PointToPlane: true
    Icp/VoxelSize: 0.05
    Icp/Epsilon: 0.001
    Icp/PointToPlaneK: 5
    Icp/PointToPlaneRadius: 0.3
    Icp/MaxCorrespondenceDistance: 0.1
    Icp/PM: true      # Use libpointmatcher to handle PointToPlane with 2d scans
    Icp/PMOutlierRatio: 0.95
    Odom/Strategy: 0
    Odom/GuessMotion: true
    Odom/ResetCountdown: 0
    Odom/ScanKeyFrameThr: 0.9

rtabmap:
    points_xyz:
      voxel_size: 0.05
      decimation: 8
      Odom/AlignWithGround: true
      
    rtabmap:
        frame_id: base_link
        map_frame_id: map
        odom_frame_id: odom
      
        subscribe_depth: false
        subscribe_rgb: false
        subscribe_rgbd: true
        subscribe_scan: true
      
        publish_tf: false
      
        Reg/Strategy: 2
        Reg/Force3DoF: true
        RGBD/ProximityBySpace: false
      
        RGBD/ProximityPathMaxNeighbors: 10
        Grid/Scan2dUnknownSpaceFilled: true
      
        Grid/FromDepth: false
        Grid/MaxGroundHeight: 0.2
        Grid/MaxObstacleHeight: 2.0
        Grid/NormalsSegmentation: false
