robot_odom:
  frequency: 100
  sensor_timeout: 0.2
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  smooth_lagged_data: true
  history_length: 0.25
  dynamic_process_noise_covariance: true
  predict_to_current_time: true
#  debug: true
#  debug_out_file: /home/jake/Documents/robot_debug/ukf_odom.txt
  
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
  
  publish_tf: true
  
  initial_state: [0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0]
  
  odom0: /frc_diff_drive_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true,  true, false,
                 false, false, false,
                 false, false, false]
  
  imu0: /imu
  imu0_differential: false
  imu0_config: [false, false, false,
                false, false, true,
                false, false, false,
                false, false, true,
                false, false, false]
