hector_mapping:
    map_frame: map
    base_frame: base_link
    odom_frame: odom

    pub_map_odom_transform: true
    pub_map_scanmatch_transform: false

    map_resolution: 0.100
    map_size: 2048
    map_multi_res_levels: 3
    map_update_angle_thresh: 0.06

    scan_topic: /scan
