rtabmap:
    rtabmap:
        frame_id: base_link
        map_frame_id: map
        odom_frame_id: odom

        publish_tf: true
      
        subscribe_depth: false
        subscribe_rgb: false
        subscribe_rgbd: true
        subscribe_scan: true
      
        queue_size: 10

        RGBD/NeighborLinkRefining: true
        RGBD/ProximityBySpace: true
        RGBD/AngularUpdate: 0.01
        RGBD/LinearUpdate: 0.01
        RGBD/OptimizeFromGraphEnd: false

        Reg/Force3DoF: true
        Reg/Strategy: 1

        Icp/VoxelSize: 0.05
        Icp/MaxCorrespondenceDistance: 0.1

        Grid/Scan2dUnknownSpaceFilled: true
        Grid/FromDepth: false
        Grid/MaxGroundHeight: 0.2
        Grid/MaxObstacleHeight: 2.0
        Grid/NormalsSegmentation: false
